#!/usr/bin/env ruby

require 'net/http'
require 'json'

http = Net::HTTP.new('localhost', 3000)
response = http.delete('/_appmap/record', {})
status = response.code.to_i
if status >= 400
  warn response.body
  exit status
end

appmap = JSON.parse(response.body)
STDOUT.write "Enter a name for the AppMap: "
name = STDIN.gets.strip
fname = "#{name}.appmap.json"
warn "Writing #{fname}"
File.write(fname, JSON.pretty_generate(appmap))
